apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args: ["echo 'sleeping for 10 seconds' && sleep 10"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts: 
    - mountPath: /tmp
      name: temp-files
  volumes: 
  - name: temp-files
    persistentVolumeClaim:
      claimName: mypvc