apiVersion: v1
kind: Pod
metadata:
  name: job-app
  labels:
    name: job-app
spec:
  containers:
  - name: job-app
    image: ubuntu
    # thats is the job
    command: ['expr', '3', '+', '2']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  # by default kubernetes is always restarting the container or pod to make sure  its working but in this case there is no service its just a dead job
  restartPolicy: Never
