apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  # its like node selector but has more values could be assigned to it
  affinity:
    nodeAffinity:
      # requiredDuringSchedulingRequiredDuringExecution:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
                  - LargeOrWhatEver
                  - Medium
      # preferredDuringSchedulingIgnoredDuringExecution:
      #   - weight: 1
      #     preference:
      #       matchExpressions:
      #         - key: disktype
      #           operator: In
      #           values:
      #             - ssd
  containers:
    - name: ubuntu
      image: ubuntu
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
