apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  # labels:
  #   app: pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # # this policy is to define what should happed when its claim gets deleted, Recycle to wait for another claim to get created, Delete to delete with it, Retain to still without attaching to another one manually or deleted manually (default)
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
