apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
    tier: frontend
  ports:
  # u can match multible port with the same service (End Point)
  - port: 80 # the trageted port (it has to be targeting the port which u want to expose)
    targetPort: 80 # simply this is the service object port (from the node)(usually it will be the same as port)
    name: myapp
    nodePort: 30001

  - port: 8080
    targetPort: 8080
    name: myapp2
    nodePort: 30002
