apiVersion: v1
kind: Pod
metadata:
  name: multi-contianer-example
  labels:
    name: multi-contianer-example
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # u might have there benifits specially when sharing the same volume
    volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  - name: alpine
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level