apiVersion: apps/v1
# stateful set is the same as Deployment but change it to StatefulSet then u have to definine the service name
kind: StatefulSet
metadata:
  name: demo-deployment-app
  labels:
    app: demo-app
spec:
  serviceName: nginx-svc
  selector:
    matchLabels:
      app: demo-app
  replicas: 3
  template:
    # nginx pods defenitions
    metadata:
      name: nginx
      labels:
        app: demo-app
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
