apiVersion: v1
kind: Pod
metadata:
  # u can even assign it through --namespace=dev
  namespace: dev
  name: namespace-demo-pod
  labels:
    name: namespace-demo-pod
spec:
  containers:
  - name: namespace-demo-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
