apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-secret
  name: pod-secret
spec:
  containers:
    - image: ubuntu
      name: pod-secret
      envFrom:
        - secretRef:
            name: sample-users
      command: ["/bin/sh", "-c"]
      args: ["env | grep USER"]
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
